# Generated by Django 3.2.13 on 2022-05-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('shipment_address', models.CharField(max_length=500)),
                ('order_date', models.DateTimeField()),
                ('expected_delivery', models.DateTimeField()),
                ('delicate_item', models.BooleanField()),
                ('fast_delivery', models.BooleanField()),
            ],
        ),
    ]
