# Generated by Django 3.2.13 on 2022-05-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='order_id',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='delicate_item',
        ),
        migrations.RemoveField(
            model_name='items',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='items',
            name='fast_delivery',
        ),
        migrations.RemoveField(
            model_name='items',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='items',
            name='shipment_address',
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_address', models.CharField(max_length=500)),
                ('order_date', models.DateTimeField()),
                ('expected_delivery', models.DateTimeField()),
                ('delicate_item', models.BooleanField()),
                ('fast_delivery', models.BooleanField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.items')),
            ],
        ),
    ]
