# Generated by Django 3.2.13 on 2022-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220522_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
