# Generated by Django 3.2.13 on 2022-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_shipment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
