# Generated by Django 3.2.13 on 2022-05-22 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_shipment_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_charge',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
